// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pudi_padi_pood.core;

#nullable disable

namespace pudi_padi.core.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20241023092000_udipudi")]
    partial class udipudi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pudi_padi.core.domain.muugi_ajalugu", b =>
                {
                    b.Property<int>("muugi_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("muugi_ID"));

                    b.Property<DateTime>("kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<string>("toode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tootaja_ID")
                        .HasColumnType("int");

                    b.HasKey("muugi_ID");

                    b.ToTable("muugi_Ajalugus");
                });

            modelBuilder.Entity("pudi_padi.core.domain.pudi_padi_pood", b =>
                {
                    b.Property<int>("poe_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("poe_ID"));

                    b.Property<string>("aadress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tel_nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tootaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tooted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("poe_ID");

                    b.ToTable("pudi_padi_poods");
                });

            modelBuilder.Entity("pudi_padi.core.domain.pusikliendid", b =>
                {
                    b.Property<int>("pusikliendi_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pusikliendi_ID"));

                    b.Property<string>("aadress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eesnimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("perenimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tel_nr")
                        .HasColumnType("int");

                    b.HasKey("pusikliendi_ID");

                    b.ToTable("pussikliendid");
                });

            modelBuilder.Entity("pudi_padi.core.domain.pusiklientide_ostuajalugu", b =>
                {
                    b.Property<int>("toode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("toode"));

                    b.Property<int>("hind")
                        .HasColumnType("int");

                    b.Property<DateTime>("kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("toote_ID")
                        .HasColumnType("int");

                    b.Property<string>("toote_info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("toote_kogus")
                        .HasColumnType("int");

                    b.HasKey("toode");

                    b.ToTable("pusiklientide_Ostuajalugus");
                });

            modelBuilder.Entity("pudi_padi.core.domain.toode", b =>
                {
                    b.Property<int>("toote_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("toote_ID"));

                    b.Property<int>("hind")
                        .HasColumnType("int");

                    b.Property<int>("kogus")
                        .HasColumnType("int");

                    b.Property<int>("kuupaev")
                        .HasColumnType("int");

                    b.Property<string>("ostuajalugu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toote_info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("toote_ID");

                    b.ToTable("toodes");
                });

            modelBuilder.Entity("pudi_padi.core.domain.tootaja", b =>
                {
                    b.Property<int>("totaja_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("totaja_ID"));

                    b.Property<string>("aadress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eesnimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("perenimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tel_nr")
                        .HasColumnType("int");

                    b.HasKey("totaja_ID");

                    b.ToTable("tootajas");
                });
#pragma warning restore 612, 618
        }
    }
}
